"""empty message

Revision ID: 89b23c80c1
Revises: 3619f8f4115
Create Date: 2014-04-27 13:46:53.210578

"""

# revision identifiers, used by Alembic.
revision = '89b23c80c1'
down_revision = '3619f8f4115'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('send_date', sa.DateTime(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    ### end Alembic commands ###
